version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - "apt update"
      - "apt install rpm -y"
      - "pip3 install boto3"
      - "curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin"
  pre_build:
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin 377877851685.dkr.ecr.eu-west-1.amazonaws.com
      - docker build -t $docker_img_name:$docker_tag .
  build:
    commands:
      - trivy i -f json -o results.json --exit-code 0 --severity HIGH,MEDIUM,LOW --quiet --auto-refresh $docker_img_name:$docker_tag
      - trivy i -f json -o results.json --exit-code 1 --severity HIGH,CRITICAL --quiet --auto-refresh $docker_img_name:$docker_tag
      - docker tag $docker_img_name:$docker_tag $ecr_repo:latest
      - docker push $ecr_repo:latest
  post_build:
    commands:
      - echo trivy scan completed on `date`
      - python3 sechub_parser.py
      - echo Report Sent to Security Hub on `date`
