version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - "apt update"
      - "apt install rpm -y"
      - "pip install --upgrade pip"
      - "pip3 install boto3"
      - "pip install trufflehog3"
      - "pip freeze"
      #- "curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin"
      - "curl -sfL https://bitbucket.org/borungbe/trivy-containerscan/raw/7db7104eae27565701cdbe2e7552e4a1a085f4d0/install.sh | sh -s -- -b /usr/local/bin"
  pre_build:
    commands:
      - echo scan repo for secrets
      - pwd
      - "> $CODEBUILD_SRC_DIR/truffletest.html"
      - trufflehog3 --no-history --format html | tee $CODEBUILD_SRC_DIR/truffletest.html
      - aws ecr get-login-password | docker login --username AWS --password-stdin 377877851685.dkr.ecr.eu-west-1.amazonaws.com
      - docker build -t $docker_img_name:$docker_tag .
  build:
    commands:
      - trivy i -f json -o $CODEBUILD_SRC_DIR/results.json --exit-code 0 --severity HIGH,MEDIUM,LOW $docker_img_name:$docker_tag
      #- trivy i -f json -o results.json --exit-code 1 --severity HIGH,CRITICAL $docker_img_name:$docker_tag
      - pwd
      - docker tag $docker_img_name:$docker_tag $ecr_repo:latest
      - docker push $ecr_repo:latest
  post_build:
    commands:
      - echo trivy scan completed on `date`
      #- python3 sechub_parser.py
      #- echo Report Sent to Security Hub on `date`
      
artifacts:
  files:
    - '**.*'
  secondary-artifacts:
    detectsecrets:
      files:
          - results.json
          - truffletest.html
